
[[_introduction]]
= Introduction

Micronaut Worker is a library for advanced scheduling and work distribution in Micronaut. Compared to the Micronaut
`@Scheduled` annotation, it adds the following capabilities

 * Custom annotations for particular use cases - `@Cron`, `@FixedDelay`, `@FixedRate`, and `@InitialDelay`
 * Runtime configuration via `worker.jobs` properties
 * Queue consumers and producers via `@QueueConsumer` and `@QueueProducer` annotations
 * Distributed processing support with optional queues and leader election
 * Job execution events `JobExecutionStartedEvent`, `JobExecutionFinishedEvent`, `JobExecutionResultEvent` and `JobExecutorEvent`
 * Built in support for https://github.com/agorapulse/micronaut-snitch[Micronaut Snitch]
 * Built in support for https://agorapulse.github.io/micronaut-console[Micronaut Console]
 * Ability to execute a single job from the CLI (for e.g. https://aws.amazon.com/batch/ or https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html)

Unlike the `@Scheduled` annotation, Micronaut Worker annotations are not repeatable, but
they can be combined in meaningful ways. For example, a method annotated with `@FixedRate('10m') @InitialDelay('1m')` executes every
ten minutes, but it will wait one minute before the first execution.

NOTE: All jobs are disabled by default in the `function` and `cli` environments, but can be triggered individually by calling `jobManager.forceRun("job-name")`.
