
[[_usage]]
= Usage

== Scheduling

The basic usage of this library is to provide an easy way to run scheduled tasks in a distributed environment.

=== Cron Jobs

To create a scheduled CRON job, annotate a bean method with `@Cron` containing the CRON definition string.

[source,java]
.Cron Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/CronSpec.groovy[tag=job-method,indent=0]
----

=== Fixed Delay Jobs

To create a fixed delay job, annotate a bean method with `@FixedDelay` containing the duration string.

[source,java]
.Fixed Delay Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/FixedDelaySpec.groovy[tag=job-method,indent=0]
----

=== Fixed Rate Jobs

To create a fixed delay job, annotate a bean method with `@FixedRate` containing the duration string.

[source,java]
.Fixed Rate Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/FixedRateSpec.groovy[tag=job-method,indent=0]
----

=== Initial Delay Jobs

To create a job with an initial delay, annotate a bean method with `@InitialDelay` containing the duration string.
This annotation can be combined with `@FixedRate` and `@FixedDelay` annotations.

[source,java]
.Initial Delay Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/InitialDelaySpec.groovy[tag=job-method,indent=0]
----

== Concurrency Management

You can limit the number of parallel executions with the `@Concurrency` annotation. The `@Consecutive` annotation
is an alias for `@Concurrency(1)` and disables parallel execution completely.

[source,java]
.Fixed Rate Job Running at Most Five Parallel Tasks
----
@Concurrency(5)
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/FixedRateSpec.groovy[tag=job-method,indent=0]
----

== Fork Options

You can spawn the method execution multiple times in parallel in a single server instance with the `@Fork` annotation.

[source,java]
.Fixed Rate Job Running at Five Parallel Tasks
----
@Fork(5)
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/FixedRateSpec.groovy[tag=job-method,indent=0]
----

[HINT]
====
You should consider using your own scheduler with the pool of the matching size:
[source,yaml]
.application.yml
----
micronaut:
  executors:
    test-job:                                                                           # <1>
      core-pool-size: 5                                                                 # <2>
worker:
  jobs:
    test-job:                                                                           # <3>
      scheduler: test-job                                                               # <4>
----
<1> The name of the new custom scheduler
<2> The size of the pool should be the same as the `fork` value
<3> The name of the job
<4> The scheduler definition using the name of the executor declared above
====

TIP: Each job can define it's owns scheduler name using `scheduler` annotation or configuration value but to prevent multiple jobs blocking each others execution, it's recommended to keep the default value. Keeping the default value will create separate executor for each job.

WARNING: For the consumer jobs, the messages are consumed synchronously so if you want to benefit from `@Fork` execution then keep the number of `maxMessages` to  the default value `1`.

== Distributed Jobs

The worker library excels in the distributed jobs area. You can run jobs only on the leader server or only on the followers or with the given concurrency level.

=== Leaders and Followers Jobs

Micronaut Worker can help you to run jobs in distributed environments. You can choose to
run the code only on the leader server or only on the followers.

[source,java]
.Leader Only Job
----
@LeaderOnly
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/CronSpec.groovy[tag=job-method,indent=0]
----

[source,java]
.Follower Only Job
----
@FollowerOnly
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/FixedRateSpec.groovy[tag=job-method,indent=0]
----

=== Jobs using Queue

In a distributed environment, tasks often process messages using queues. In Micronaut Worker,
you have three type of queue related jobs - producers, consumers and pipes - depending on the number of
arguments they have and their return value.

==== Quick Start

You can use two conventional annotations `@QueueProducer` and `@QueueConsumer` to publish and consume messages from a queue.

[source,java]
.Queue Producer and Consumer
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/convention/QueueListenerAndProducerSpec.groovy[tag=quickstart,indent=0]
----
<1> Two jobs will communicate to each other using the given record object
<2> The producer jobs must have some scheduled trigger associated with them, for example cron or fixed rate
<3> Use the `@QueueProducer` annotation with the name of the queue to publish messages
<4> The producer job must return some value, ideally a `Publisher` of given messages
<5> Use the `@QueueConsumer` annotation with the name of the queue to consume messages
<6> The consumer job must have a single parameter of the same type as the producer job returns

TIP: The value for `@Fork` is the same as the number of `maxMessages` for `@QueueConsumer` annotation. The value of `waitingTime` in `@QueueConsumer` is the same as the associated `@FixedRate` value.

==== Advanced Usage

The name of the queue can be customised using `@Consumes` and `@Produces`
annotations, otherwise the name is derived from the simple name of the class with any `Job`, `Consumer`, or `Producer`
suffix (in this order recursively). If the `micronaut.application.name` property is set, the
extracted name is prefixed with the application name followed by an underscore. For example,
with `micronaut.application.name` set to `myapp`, `MyOwnConsumerJob` will have the
default queue name `myapp_MyOwn`.

==== Producer

Producer jobs return a value, usually a `Publisher`, collection of objects, or a single object.
Producer jobs are always run only on the leader server.

[source,java]
.Producer Job
----
include::{root-dir}/libs/micronaut-worker-tck/src/main/groovy/com/agorapulse/worker/tck/queue/SendWordsJob.groovy[tag=simple-producer-method,indent=0]
----

TIP: If the producer job returns a `Publisher`, the messages can be batched if underlying implementation supports it. At the moment, only SQS AWS v2 implementation supports batching.

==== Consumer

Consumer jobs take a single parameter. They are usually a `@FixedRate` job waiting for a message from a queue.
Messages can be sent into the queue from external systems, a producer job, or using `JobManager#enqueue` method.

[source,java]
.Consumer Job
----
include::{root-dir}/libs/micronaut-worker-tck/src/main/groovy/com/agorapulse/worker/tck/queue/SendWordsJob.groovy[tag=simple-consumer-method,indent=0]
----

==== Pipe

Pipe jobs are a combination of producer and consumer jobs. They usually use `@Consumes` and `@Produces`
to specify the source, and the destination name of the queue.

[source,java]
.Pipe Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/PipeSpec.groovy[tag=job-method,indent=0]
----

As with a consumer job, you can use `JobManager#enqueue` to send messages to the job.

[source,java]
.Send Message to Job
----
include::{root-dir}/libs/micronaut-worker/src/test/groovy/com/agorapulse/worker/annotation/PipeSpec.groovy[tag=enqueue,indent=0]
----

== Configuration

=== General Settings

You can disable all jobs by setting `worker.enabled` to `false`:

[source,yaml]
.Disabling All Jobs
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-disabled.yml[]
----

NOTE: All jobs are disabled for the `test` and `function` environments.

You can set the default queue type using the `worker.queue-type` configuration property. This is convenient for local development to ensure your application is running against the local implementation.

[source,yaml]
.Setting the Default Queue Type
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-local.yml[]
----

You can override the default scheduler (`TaskExecutors.SCHEDULED`) by setting the `worker.scheduler` property.

[source,yaml]
.Setting the Default Scheduler
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-virtual.yml[]
----

TIP: You can let your jobs executed using virtual threads by using `virtual` executor.

=== Job Configuration

Anything you can configure using annotations can be configured externally.
The name of the job for classes having just a single job method is the name of the class hyphenated, e.g., `sample-job`
for a class `SampleJob`. If the class contains more than one job method, jobs are created
for each method, and the name contains both the simple class name and the name of the method, e.g.,
`sample-job-method-one` for `SampleJob#methodOne`. You can override the default name by using
`@Named("another-name")`. The custom name must already be hyphenated.

You can individually disable specific jobs:

[source,yaml]
.Disabling Single Job
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-disabled-individual.yml[]
----

You can even change the type of the job:

[source,yaml]
.Switch to Cron Job
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-cron.yml[]
----

WARNING: You can only use one of `cron`, `fixed-delay`, and `fixed-rate` settings. If more than one
is used, the first of `cron`, `fixed-delay` or `fixed-rate` is selected in this particular order. You can use `initial-delay` either individually or with `fixed-delay` or `fixed-rate` settings.

You can change the concurrency level and leader/follower execution:

[source,yaml]
.Concurrency Selection
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-concurrency.yml[]
----

You can configure the consumer and producer queues for distributed jobs.

[source,yaml]
.Queues Customisation
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/application-queues.yml[]
----

== Events

There are currently three events being fired:

  * `JobExecutionStartedEvent` - fired before executing the job
  * `JobExecutionFinishedEvent` - fired after execution
  * `JobExecutionResultEvent` - fired after execution of a producer or pipe job

WARNING: The `JobExecutionResultEvent` contains a reference to the `result` of the execution. Any modifications of the `result` may cause unexpected behavior.

The basic example (already present in the codebase) is simple logging:

[source,java]
.Logging Job Execution using Events
----
include::{root-dir}/libs/micronaut-worker/src/main/java/com/agorapulse/worker/event/JobEventsLogger.java[lines=18..-1,options="nowrap"]
----

TIP: If https://github.com/agorapulse/micronaut-snitch[Micronaut Snitch] is present on the classpath and configured with the name of the job, the `snitch` method is called automatically after successful execution.

== CLI Runner

You can run a single job from the command line using the `com.agorapulse.worker.runner.JobRunner` class as the main class. The arguments are the names of the jobs to run. All other jobs are disabled, even when enabled in the configuration (see corner cases below). The application will run until all jobs are finished.

[source,shell]
.Run Job from CLI
----
java -cp myapp-shadow.jar com.agorapulse.worker.runner.JobRunner sample-job other-job
----

WARNING: In some corner cases, some unrelated jobs can still be executed if they have a very short delay or frequency if they are manually enabled in the configuration. Please, prefer annotation driven jobs over configuring them manually in the configuration to avoid this issue.

== Management

You can use `jobs` management endpoint, by default located at `/jobs`, to see the status of all the jobs in the application.

[source,json]
.Jobs Response
----
include::{root-dir}/libs/micronaut-worker-management/src/test/resources/com/agorapulse/worker/management/JobsEndpointSpec/jobs.json[]
----

== Console Integration

For security reasons, Micronaut Worker does not provide any management endpoint, but it integrates with
https://agorapulse.github.io/micronaut-console[Micronaut Console] to monitor the jobs and event to trigger them manually.

An instance of `JobManager` aliased as `jobs` is added to the script bindings. There is a also variable added for
each job. The name is the lower-camel-case version of the job name, e.g., `sampleJob` for the `sample-job` job.

[source]
.Additional Binding into Micoronaut Console
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/variables.txt[]
----

TIP: The job variables are instances of `JobAccessor`, which also provides methods `run()` and `enqueue(message)` to let you easily trigger jobs from the console. You can also use method `reconfigure(consumer)` that changes the in-memory configuration of the job and reschedules it.

A simple script with just variable `jobs` will print the status of the current job execution. Depending
on which console endpoint you choose, you get either a text or JSON summary.

[source,groovy]
.Job Manager Script
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/listJobs.groovy[]
----

[source,options="nowrap"]
.Job Manager Script - Text Result
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/listJobsResponse.txt[]
----

[source]
.Job Manager Script - JSON Result
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/listJobsResponse.json[]
----

Reconfiguring the job will try to change the configuration of the job and reschedule it if it's still enabled.

[source,options="nowrap"]
.Job Manager Script - Reconfigure
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/reconfigure.groovy[]
----

Returning a job variable from the script will render details for that job.

[source,groovy]
.Job Detail Script
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/oneJob.groovy[]
----

[source,options="nowrap"]
.Job Detail Script - Text Result
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/oneJobResponse.txt[]
----


[source]
.Job Detail Script - JSON Result
----
include::{root-dir}/libs/micronaut-worker/src/test/resources/com/agorapulse/worker/console/ConsoleSpec/oneJobResponse.json[]
----
