name: Manual Publish Documentation

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: gradle
      - name: Get the Latest Release
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Publish Docs
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: migrateImports gitPublishPush -x groovydoc -x aggregateGroovydoc -Pversion=${{ steps.previoustag.outputs.tag }}-micronaut-3.0 -Prelease=true --stacktrace -PmicronautVersion=3.2.3 -PspockVersion=2.0-groovy-3.0 -PgroovyVersion=3.0.9 -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
