name: Release

on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Decode PGP
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.pgp'
          encodedString: ${{ secrets.SIGNING_SECRET_KEY_BASE64 }}
      - name: Release
        env:
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        uses: gradle/gradle-command-action@v2
        with:
          arguments: gitPublishPush publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.tag }} -Prelease=true --stacktrace -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
          - agorapulse/agorapulse-oss
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse", "module": "micronaut-worker", "micronautCompatibility": [4], "version": "${{ steps.version.outputs.tag }}", "property" : "micronaut.worker.version", "github" : ${{ toJson(github) }} }'
